import { useAuth } from "@/_core/hooks/useAuth";
import PublicLayout from "@/components/PublicLayout";
import { trpc } from "@/lib/trpc";
import { BarChart3, BookOpenCheck, Eye, Heart, Star } from "lucide-react";

export default function AuthorAnalytics() {
  const { isAuthenticated, user } = useAuth();
  const allowed = user?.role === "editor" || user?.role === "admin" || user?.role === "super_admin";
  const { data, isLoading } = trpc.community.authorAnalytics.useQuery(undefined, { enabled: isAuthenticated && allowed });
  if (!isAuthenticated) return <PublicLayout><div className="container py-24 text-center"><h1 className="font-serif text-4xl">سجّل الدخول لعرض مؤشرات أعمالك</h1></div></PublicLayout>;
  if (!allowed) return <PublicLayout><div className="container py-24 text-center"><h1 className="font-serif text-4xl">هذه الصفحة متاحة للمحررين والمديرين فقط</h1></div></PublicLayout>;
  return <PublicLayout><section className="container py-16"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#af7c42]/10 p-3"><BarChart3 className="h-6 w-6 text-[#af7c42]" /></div><div><p className="text-sm font-bold text-[#af7c42]">مؤشرات المؤلف</p><h1 className="font-serif text-4xl text-[#1d2940]">أداء الأعمال المنشورة</h1></div></div><p className="mt-4 max-w-3xl text-sm leading-7 text-[#667085]">تُحتسب هذه المؤشرات من نشاط القراء الفعلي: الفتحات، الإكمال، الإضافات للمفضلة، والتقييمات الشخصية.</p>{isLoading ? <div className="mt-8 h-64 animate-pulse rounded-2xl bg-[#e9dfca]" /> : data?.length ? <div className="mt-8 overflow-hidden rounded-2xl border border-[#1d2940]/10 bg-white"><div className="grid grid-cols-[minmax(10rem,1fr)_repeat(4,auto)] gap-4 border-b border-[#1d2940]/10 bg-[#fbf8f2] px-5 py-3 text-xs font-bold text-[#53627a]"><span>الرواية</span><span>قراءات</span><span>إكمال</span><span>مفضلة</span><span>تقييم</span></div>{data.map(item => <div key={item.id} className="grid grid-cols-[minmax(10rem,1fr)_repeat(4,auto)] items-center gap-4 border-b border-[#1d2940]/8 px-5 py-4 last:border-0"><div><strong className="block font-serif text-lg text-[#1d2940]">{item.title}</strong><span className="text-xs text-[#667085]">{item.chapterCount} فصلًا</span></div><span className="inline-flex items-center gap-1 text-sm text-[#53627a]"><Eye className="h-3.5 w-3.5 text-[#af7c42]" />{item.views}</span><span className="inline-flex items-center gap-1 text-sm text-[#53627a]"><BookOpenCheck className="h-3.5 w-3.5 text-[#af7c42]" />{item.completions}</span><span className="inline-flex items-center gap-1 text-sm text-[#53627a]"><Heart className="h-3.5 w-3.5 text-[#af7c42]" />{item.favorites}</span><span className="inline-flex items-center gap-1 text-sm text-[#53627a]"><Star className="h-3.5 w-3.5 fill-[#af7c42] text-[#af7c42]" />{Number(item.averageRating).toFixed(1)}</span></div>)}</div> : <p className="mt-8 rounded-2xl border border-dashed border-[#af7c42]/30 p-8 text-center text-sm text-[#667085]">ستظهر مؤشرات الأعمال التي نشرتها بعد وجود تفاعل فعلي من القراء.</p>}</section></PublicLayout>;
}
