import PublicLayout from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { useState } from "react";

const documents: Record<string, {title:string; intro:string; sections:{heading:string; body:string}[]}> = {
  privacy:{title:"الخصوصية",intro:"توضح هذه السياسة كيفية التعامل مع البيانات اللازمة لتشغيل تجربة القراءة والحسابات في منصة روايتك بالعربية.",sections:[{heading:"البيانات التي نجمعها",body:"قد نجمع بيانات الحساب الأساسية، وتفضيلات القراءة، وبيانات تقنية مختصرة لازمة لحماية المنصة وتحسين أدائها."},{heading:"استخدام البيانات",body:"تستخدم البيانات لتشغيل الحساب، وحفظ موضع القراءة عند تفعيل الميزة، وحماية النظام، وإرسال الإشعارات التي يختارها المستخدم."},{heading:"حقوق المستخدم",body:"يمكن للمستخدم طلب الوصول إلى بياناته أو تصحيحها أو حذفها وفق الإجراءات التي يعلنها مشغّل المنصة."}]},
  terms:{title:"شروط الاستخدام",intro:"باستخدامك المنصة، توافق على احترام المحتوى الأدبي وحقوق أصحابه واستخدام الخدمات في إطار قانوني ومسؤول.",sections:[{heading:"الوصول إلى المحتوى",body:"يُتاح المحتوى المنشور للقراءة وفق الحالة التي تحددها الإدارة. لا يمنح الوصول حق النسخ أو إعادة النشر أو التوزيع من دون إذن."},{heading:"الحسابات",body:"المستخدم مسؤول عن المحافظة على سرية بيانات دخوله وعن صحة المعلومات التي يقدمها في حسابه."},{heading:"التغييرات",body:"قد تُحدّث الشروط عند تطور الخدمة، ويُعلن عن النسخة السارية في هذه الصفحة."}]},
  content:{title:"سياسة المحتوى",intro:"تلتزم المنصة بإدارة المحتوى الأدبي مركزيًا وتقديمه في مساحة تحترم القارئ والمؤلف وحقوق العمل.",sections:[{heading:"نطاق النشر",body:"لا تتيح المنصة النشر المفتوح للجمهور. يخضع كل عمل لدورة إنشاء ومراجعة ونشر تديرها الجهة المشغلة."},{heading:"المحتوى المقبول",body:"يجب أن يكون المحتوى مشروعًا ومملوكًا أو مرخّصًا للجهة الناشرة، وألا ينتهك الحقوق أو يعرّض المستخدمين لمحتوى ضار أو مخالف للقانون."},{heading:"المراجعة والإزالة",body:"يحق للإدارة تعليق المحتوى أو إلغاؤه أو أرشفته عند اكتشاف مشكلة حقوقية أو مخالفة لسياسة المنصة."}]},
  copyright:{title:"حقوق النشر",intro:"تحترم روايتك بالعربية الملكية الفكرية وتعمل على إدارة المحتوى الأدبي وفق مصادره وحقوق نشره.",sections:[{heading:"مصدر المحتوى",body:"تحتفظ الإدارة بسجل مصدر المحتوى ومعلومات الحقوق المتاحة لكل عمل منشور."},{heading:"بلاغات الانتهاك",body:"يمكن لصاحب الحق أو ممثله إرسال بلاغ واضح يتضمن تعريف العمل والملكية والرابط محل الاعتراض ووسيلة تواصل موثوقة."},{heading:"الاستجابة",body:"تراجع الإدارة البلاغات وتتصرف بما يلزم، بما في ذلك تعليق المحتوى أو إزالته عند ثبوت وجود مخالفة."}]}
  ,contact:{title:"تواصل معنا",intro:"نرحب بالملاحظات والاستفسارات وبلاغات الحقوق المتعلقة بمحتوى المنصة أو عملها.",sections:[{heading:"الاستفسارات العامة",body:"أضف وسيلة التواصل الرسمية للمنصة من إعدادات التشغيل قبل الإطلاق، وحدد أوقات الاستجابة المناسبة لفريق الإدارة."},{heading:"بلاغات حقوق النشر",body:"يرجى تضمين اسم صاحب الحق، والعمل محل البلاغ، والرابط المباشر، ووصفًا واضحًا للعلاقة بالعمل، ووسيلة اتصال موثوقة."},{heading:"الدعم الفني",body:"للمشكلات التقنية، أرسل وصفًا مختصرًا للخطأ والجهاز والمتصفح ووقت حدوث المشكلة لمساعدة فريق المنصة على التحقيق."}]}
};
export default function Legal({document}:{document:string}){const item=documents[document]||documents.privacy; const { user } = useAuth(); const [form, setForm] = useState({ name: user?.name ?? "", email: user?.email ?? "", subject: "", message: "" }); const sendMessage = trpc.contact.send.useMutation({ onSuccess: () => setForm(current => ({ ...current, subject: "", message: "" })) }); return <PublicLayout><section className="container max-w-3xl py-16 md:py-24"><p className="text-xs font-bold tracking-[.18em] text-[#af7c42]">وثائق المنصة</p><h1 className="mt-3 font-serif text-5xl">{item.title}</h1><p className="mt-6 text-lg leading-9 text-[#526071]">{item.intro}</p>{document === "contact" ? <form className="mt-10 grid gap-4 rounded-2xl border border-border bg-card p-6" onSubmit={event => { event.preventDefault(); sendMessage.mutate(form); }}><h2 className="font-serif text-2xl">أرسل رسالتك</h2><div className="grid gap-4 sm:grid-cols-2"><input required minLength={2} maxLength={160} value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} placeholder="الاسم" className="h-11 rounded-xl border border-border bg-background px-3" /><input required type="email" maxLength={320} value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} placeholder="البريد الإلكتروني" className="h-11 rounded-xl border border-border bg-background px-3" /></div><input required minLength={3} maxLength={220} value={form.subject} onChange={event => setForm({ ...form, subject: event.target.value })} placeholder="موضوع الرسالة" className="h-11 rounded-xl border border-border bg-background px-3" /><textarea required minLength={10} maxLength={5000} value={form.message} onChange={event => setForm({ ...form, message: event.target.value })} placeholder="اكتب رسالتك هنا" className="min-h-36 rounded-xl border border-border bg-background p-3" /><Button type="submit" disabled={sendMessage.isPending}>{sendMessage.isPending ? "جارٍ الإرسال..." : "إرسال الرسالة"}</Button>{sendMessage.isSuccess ? <p className="text-sm text-emerald-600">تم إرسال رسالتك إلى إدارة المنصة.</p> : null}{sendMessage.error ? <p className="text-sm text-destructive">تعذر إرسال الرسالة، تحقق من البيانات وحاول مرة أخرى.</p> : null}</form> : null}<div className="mt-12 space-y-10">{item.sections.map(section=><section key={section.heading}><h2 className="font-serif text-3xl">{section.heading}</h2><p className="mt-3 leading-8 text-[#435063]">{section.body}</p></section>)}</div><p className="mt-14 border-t border-[#1d2940]/10 pt-5 text-sm text-[#667085]">هذه صياغة تشغيلية أولية، ويجب مراجعتها قانونيًا قبل الإطلاق العام وفق الجهة المشغّلة ونطاق الخدمة.</p></section></PublicLayout>;}
