import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import PublicLayout from "@/components/PublicLayout";
import AdPlacement from "@/components/AdPlacement";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BookOpen, ChevronLeft, Clock3, Heart, List, Rss, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Link } from "wouter";

export default function NovelDetail({ slug }: { slug: string }) {
  const { data: novel, isLoading } = trpc.catalog.detail.useQuery({ slug });
  const { isAuthenticated } = useAuth();
  const [favorite, setFavorite] = useState(false);
  const [following, setFollowing] = useState(false);
  const favoriteMutation = trpc.library.toggleFavorite.useMutation({ onSuccess: result => { setFavorite(result.active); toast.success(result.active ? "أُضيفت إلى المفضلة." : "أُزيلت من المفضلة."); } });
  const followMutation = trpc.library.toggleFollow.useMutation({ onSuccess: result => { setFollowing(result.active); toast.success(result.active ? "ستصلك إشعارات الفصول الجديدة." : "أُوقفت متابعة الرواية."); } });
  const requireLogin = (action: () => void) => isAuthenticated ? action() : startLogin();
  if (isLoading) return <PublicLayout><div className="container py-28"><div className="h-96 animate-pulse rounded-3xl bg-[#e9dfca]" /></div></PublicLayout>;
  if (!novel) return <PublicLayout><div className="container py-28 text-center"><h1 className="font-serif text-4xl">هذه الرواية غير متاحة</h1><Link href="/novels" className="mt-5 inline-block text-[#af7c42]">العودة إلى المكتبة</Link></div></PublicLayout>;
  const first = novel.chapters[0];
  return <PublicLayout>
    <section className="border-b border-[#1d2940]/10 bg-[#e9dfca]/45"><div className="container grid gap-10 py-12 md:grid-cols-[250px_1fr] md:py-20"><div className="mx-auto w-full max-w-[250px] overflow-hidden rounded-[1.5rem] bg-[#1d2940] shadow-2xl shadow-[#1d2940]/20">{novel.coverUrl ? <img src={novel.coverUrl} alt={novel.coverAlt || `غلاف ${novel.title}`} className="aspect-[3/4] w-full object-cover" /> : <div className="flex aspect-[3/4] items-end bg-[radial-gradient(circle_at_top,#41516f,#1d2940_68%)] p-7 font-serif text-3xl text-[#f6f1e7]">{novel.title}</div>}</div><div className="self-center"><Link href={`/authors/${novel.authorSlug}`} className="inline-flex items-center gap-2 text-sm font-bold text-[#af7c42]"><UserRound className="h-4 w-4" />{novel.authorName}</Link><h1 className="mt-4 font-serif text-5xl leading-tight md:text-6xl">{novel.title}</h1>{novel.subtitle && <p className="mt-3 text-lg text-[#526071]">{novel.subtitle}</p>}<p className="mt-6 max-w-2xl leading-8 text-[#526071]">{novel.shortDescription || "تفاصيل هذه الرواية ستظهر هنا بعد إضافة النبذة من لوحة الإدارة."}</p><div className="mt-6 flex flex-wrap gap-2">{novel.categories.map(category => <Link key={category.slug} href={`/categories/${category.slug}`} className="rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#526071]">{category.name}</Link>)}{novel.tags.map(tag => <span key={tag.slug} className="rounded-full border border-[#af7c42]/35 px-3 py-1.5 text-xs text-[#af7c42]">#{tag.name}</span>)}</div><div className="mt-8 flex flex-wrap gap-3">{first ? <Link href={`/read/${novel.slug}/${first.slug}`}><Button className="h-12 bg-[#1d2940] px-6 text-[#f6f1e7] hover:bg-[#33435e]"><BookOpen className="ml-2 h-4 w-4" />ابدأ القراءة</Button></Link> : <Button disabled className="h-12">الفصول قريبًا</Button>}<Button variant="outline" className={`h-12 border-[#1d2940]/20 bg-transparent ${favorite ? "bg-[#e9dfca]" : ""}`} onClick={() => requireLogin(() => favoriteMutation.mutate({ novelId: novel.id }))}><Heart className={`ml-2 h-4 w-4 ${favorite ? "fill-current" : ""}`} />{favorite ? "في المفضلة" : "حفظ للراغبين"}</Button><Button variant="outline" className={`h-12 border-[#1d2940]/20 bg-transparent ${following ? "bg-[#e9dfca]" : ""}`} onClick={() => requireLogin(() => followMutation.mutate({ novelId: novel.id }))}><Rss className="ml-2 h-4 w-4" />{following ? "تتابع الرواية" : "تابع الفصول"}</Button></div><div className="mt-7 flex gap-6 text-sm text-[#667085]"><span className="inline-flex items-center gap-2"><List className="h-4 w-4 text-[#af7c42]" />{novel.chapters.length} فصلًا منشورًا</span><span className="inline-flex items-center gap-2"><Clock3 className="h-4 w-4 text-[#af7c42]" />آخر تحديث {new Date(novel.updatedAt).toLocaleDateString("ar")}</span></div></div></div></section>
    <section className="container grid gap-14 py-16 lg:grid-cols-[1fr_320px]"><div><h2 className="font-serif text-3xl">عن الرواية</h2><p className="mt-5 whitespace-pre-line leading-9 text-[#435063]">{novel.description || novel.shortDescription || "لم تُضف نبذة تفصيلية بعد."}</p><AdPlacement placement="novel" /></div><aside className="rounded-2xl border border-[#1d2940]/10 bg-white p-5"><div className="flex items-center gap-2 text-sm font-bold"><List className="h-4 w-4 text-[#af7c42]" />فصول الرواية</div><ol className="mt-4 divide-y divide-[#1d2940]/8">{novel.chapters.map(chapter => <li key={chapter.id}><Link href={`/read/${novel.slug}/${chapter.slug}`} className="flex items-center justify-between gap-3 py-3 text-sm hover:text-[#af7c42]"><span><span className="ml-2 text-[#af7c42]">{String(chapter.sortOrder).padStart(2, "0")}</span>{chapter.title}</span><ChevronLeft className="h-4 w-4" /></Link></li>)}{!novel.chapters.length && <li className="py-4 text-sm text-[#667085]">لا توجد فصول منشورة.</li>}</ol></aside></section>
    {novel.related.length > 0 && <section className="border-t border-[#1d2940]/10 bg-[#e9dfca]/35"><div className="container py-14"><h2 className="font-serif text-3xl">أعمال أخرى للمؤلف</h2><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{novel.related.map(item => <Link key={item.id} href={`/novels/${item.slug}`} className="rounded-xl bg-white p-4 text-sm shadow-sm hover:shadow-md"><strong className="font-serif text-lg">{item.title}</strong><span className="mt-2 block text-xs text-[#667085]">{item.chapterCount} فصلًا</span></Link>)}</div></div></section>}
  </PublicLayout>;
}
