import PublicLayout from "@/components/PublicLayout";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { BadgeCheck, CalendarDays, Gift, Loader2, Sparkles, Trophy } from "lucide-react";
import { Link } from "wouter";

export default function Rewards() {
  const { user, loading } = useAuth({ redirectOnUnauthenticated: true, redirectPath: "/rewards" });
  const rewards = trpc.profile.myRewards.useQuery(undefined, { enabled: Boolean(user) });
  if (loading || rewards.isLoading) return <PublicLayout><div className="container grid min-h-[60vh] place-items-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div></PublicLayout>;
  if (!user) return null;
  return <PublicLayout><main className="container max-w-5xl py-12 md:py-16" dir="rtl"><section className="rounded-3xl border border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card p-7 md:p-10"><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="flex items-center gap-2 text-sm font-bold text-primary"><Gift className="h-4 w-4" />مساحتي الخاصة</p><h1 className="mt-2 font-serif text-4xl">مكافآتي</h1><p className="mt-3 max-w-2xl leading-8 text-muted-foreground">هنا تجد الشارات والمزايا التي استبدلتها بنقاطك، مع تاريخ كل عملية لتبقى مكافآتك منظمة وواضحة.</p></div><div className="grid h-16 w-16 place-items-center rounded-2xl bg-primary/10 text-primary"><Trophy className="h-8 w-8" /></div></div></section><section className="mt-8">{rewards.error ? <Card><CardContent className="p-8 text-center"><p className="text-destructive">تعذر تحميل مكافآتك حاليًا.</p><Button className="mt-4" onClick={() => void rewards.refetch()}>إعادة المحاولة</Button></CardContent></Card> : rewards.data?.length ? <div className="grid gap-5 md:grid-cols-2">{rewards.data.map(item => <Card key={`${item.rewardKey}-${item.redeemedAt}`} className="overflow-hidden border-border transition-shadow hover:shadow-md"><CardContent className="p-6"><div className="flex items-start justify-between gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-primary/10 text-primary">{item.reward?.kind === "badge" ? <BadgeCheck className="h-7 w-7" /> : <Sparkles className="h-7 w-7" />}</div><Badge variant={item.reward?.kind === "badge" ? "default" : "secondary"}>{item.reward?.kind === "badge" ? "شارة مميزة" : "ميزة حصرية"}</Badge></div><h2 className="mt-5 font-serif text-2xl">{item.reward?.title ?? "مكافأة"}</h2><p className="mt-2 leading-7 text-muted-foreground">{item.reward?.description}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-border pt-4 text-sm"><span className="flex items-center gap-2 text-muted-foreground"><CalendarDays className="h-4 w-4 text-primary" />تاريخ الاستبدال</span><time dateTime={new Date(item.redeemedAt).toISOString()} className="font-semibold">{new Date(item.redeemedAt).toLocaleString("ar-EG")}</time></div><div className="mt-3 text-xs text-muted-foreground">تم خصم {item.pointsCost} نقطة من رصيدك</div></CardContent></Card>)}</div> : <Card className="border-dashed"><CardContent className="p-10 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-primary/10 text-primary"><Gift className="h-8 w-8" /></div><h2 className="mt-5 font-serif text-2xl">لم تستبدل مكافآت بعد</h2><p className="mx-auto mt-2 max-w-lg leading-7 text-muted-foreground">ابدأ بجمع النقاط من القراءة والتقييمات واقتراحات الترجمة، ثم اختر مكافأتك من متجر النقاط.</p><Button asChild className="mt-5"><Link href="/profile">العودة إلى متجر النقاط</Link></Button></CardContent></Card>}</section></main></PublicLayout>;
}
