import BookCard from "@/components/BookCard";
import PublicLayout from "@/components/PublicLayout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Search } from "lucide-react";
import { useState } from "react";

export default function SearchPage() { const initial = new URLSearchParams(window.location.search).get("q") || ""; const [query, setQuery] = useState(initial); const [submitted, setSubmitted] = useState(initial); const {data,isLoading}=trpc.catalog.listNovels.useQuery({query:submitted||undefined,limit:36}); return <PublicLayout><section className="container py-14 md:py-20"><p className="text-xs font-bold tracking-[.18em] text-[#af7c42]">اكتشاف</p><h1 className="mt-2 font-serif text-5xl">ابحث في الحكايات</h1><form className="mt-8 flex max-w-2xl items-center rounded-2xl border border-[#1d2940]/15 bg-white p-2" onSubmit={event=>{event.preventDefault();setSubmitted(query.trim())}}><Search className="mr-3 h-5 w-5 text-[#af7c42]"/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="عنوان، مؤلف، تصنيف أو وسم..." className="h-12 border-0 bg-transparent shadow-none focus-visible:ring-0"/><Button type="submit" className="h-12 bg-[#1d2940] px-6">بحث</Button></form></section><section className="container pb-24">{submitted && <p className="mb-6 text-sm text-[#667085]">نتائج البحث عن <strong className="text-[#1d2940]">«{submitted}»</strong></p>}{isLoading?<div className="grid grid-cols-2 gap-5 sm:grid-cols-3 lg:grid-cols-6">{Array.from({length:6}).map((_,i)=><div key={i} className="aspect-[3/4] animate-pulse rounded-2xl bg-[#e9dfca]"/>)}</div>:data?.length?<div className="grid grid-cols-2 gap-x-5 gap-y-10 sm:grid-cols-3 lg:grid-cols-6">{data.map(novel=><BookCard key={novel.id} novel={novel}/>)}</div>:<div className="rounded-2xl border border-dashed border-[#af7c42]/40 py-16 text-center"><h2 className="font-serif text-2xl">لم نعثر على نتيجة بعد</h2><p className="mt-2 text-sm text-[#667085]">يدعم البحث العناوين والمؤلفين والتصنيفات والوسوم العربية.</p></div>}</section></PublicLayout>; }
