import AdminShell from "@/components/AdminShell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { Megaphone, Plus } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AdminAds() { const utils=trpc.useUtils(); const {data}=trpc.ads.list.useQuery(); const [form,setForm]=useState({placement:"home" as "home"|"category"|"novel",label:"",provider:"",slotCode:"",isEnabled:false}); const save=trpc.ads.upsert.useMutation({onSuccess:()=>{toast.success("حُفظ موضع الإعلان.");setForm({placement:"home",label:"",provider:"",slotCode:"",isEnabled:false});utils.ads.list.invalidate();}}); return <AdminShell title="مواضع الإعلانات" description="أنشئ مواضع إعلانية في الصفحات العامة فقط؛ واجهة القراءة مستثناة لضمان تجربة بلا تشتيت."><div className="grid gap-7 lg:grid-cols-[380px_1fr]"><form className="rounded-2xl border border-[#1d2940]/10 bg-white p-5" onSubmit={e=>{e.preventDefault();save.mutate(form)}}><div className="flex items-center justify-between"><h2 className="font-serif text-2xl">موضع جديد</h2><Megaphone className="h-5 w-5 text-[#af7c42]"/></div><div className="mt-5 grid gap-3"><Select value={form.placement} onValueChange={value=>setForm(current=>({...current,placement:value as typeof form.placement}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="home">الرئيسية</SelectItem><SelectItem value="category">التصنيفات</SelectItem><SelectItem value="novel">صفحة الرواية</SelectItem></SelectContent></Select><Input required value={form.label} onChange={e=>setForm(current=>({...current,label:e.target.value}))} placeholder="اسم الموضع"/><Input value={form.provider} onChange={e=>setForm(current=>({...current,provider:e.target.value}))} placeholder="المزوّد (اختياري)"/><Input value={form.slotCode} onChange={e=>setForm(current=>({...current,slotCode:e.target.value}))} placeholder="رمز الموضع (اختياري)"/><label className="flex items-center justify-between text-sm"><span>تفعيل الموضع</span><Switch checked={form.isEnabled} onCheckedChange={value=>setForm(current=>({...current,isEnabled:value}))}/></label></div><Button className="mt-4 bg-[#1d2940]" type="submit"><Plus className="ml-2 h-4 w-4"/>حفظ</Button></form><section className="rounded-2xl border border-[#1d2940]/10 bg-white p-5"><h2 className="font-serif text-2xl">المواضع الحالية</h2><div className="mt-4 divide-y divide-[#1d2940]/8">{data?.length?data.map(item=><div key={item.id} className="flex items-center justify-between py-4"><span><strong className="block">{item.label}</strong><small className="text-[#667085]">{item.placement} · {item.provider||"غير مرتبط"}</small></span><span className={`text-xs font-semibold ${item.isEnabled?"text-[#317251]":"text-[#667085]"}`}>{item.isEnabled?"مفعل":"معطل"}</span></div>):<p className="py-8 text-sm text-[#667085]">لا توجد مواضع إعلانية بعد.</p>}</div></section></div></AdminShell> }
