import AdminShell from "@/components/AdminShell";
import { Button } from "@/components/ui/button";
import MediaPicker from "@/components/MediaPicker";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Archive, ArrowDown, ArrowUp, BookOpen, Edit3, ListPlus, Plus } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type PublicationStatus = "draft" | "review" | "published" | "unpublished" | "archived";
type NovelForm = { id?: number; authorId: string; title: string; subtitle: string; slug: string; shortDescription: string; description: string; coverMediaId: string; status: PublicationStatus; isFeatured: boolean };
type ChapterForm = { id?: number; title: string; slug: string; sortOrder: string; content: string; excerpt: string; status: PublicationStatus };
const freshNovel: NovelForm = { authorId: "", title: "", subtitle: "", slug: "", shortDescription: "", description: "", coverMediaId: "", status: "draft", isFeatured: false };
const freshChapter: ChapterForm = { title: "", slug: "", sortOrder: "1", content: "", excerpt: "", status: "draft" };

export default function AdminNovels() {
  const utils = trpc.useUtils();
  const { data: authors } = trpc.admin.listAuthors.useQuery({ limit: 48 });
  const { data: novels, isLoading } = trpc.admin.listNovels.useQuery({ limit: 48 });
  const [selectedNovelId, setSelectedNovelId] = useState<number | undefined>();
  const { data: chapters } = trpc.admin.listChapters.useQuery({ novelId: selectedNovelId! }, { enabled: Boolean(selectedNovelId) });
  const [novelForm, setNovelForm] = useState<NovelForm>(freshNovel);
  const [chapterForm, setChapterForm] = useState<ChapterForm>(freshChapter);
  const selected = useMemo(() => novels?.find(novel => novel.id === selectedNovelId), [novels, selectedNovelId]);
  const createNovel = trpc.admin.upsertNovel.useMutation({ onSuccess: () => { toast.success(novelForm.id ? "حُدّثت الرواية." : "حُفظت الرواية."); setNovelForm(freshNovel); utils.admin.listNovels.invalidate(); } });
  const saveChapter = trpc.admin.upsertChapter.useMutation({ onSuccess: () => { toast.success(chapterForm.id ? "حُدّث الفصل." : "حُفظ الفصل."); setChapterForm({ ...freshChapter, sortOrder: String((chapters?.length || 0) + 2) }); utils.admin.listChapters.invalidate(); utils.admin.listNovels.invalidate(); } });
  const reorder = trpc.admin.reorderChapters.useMutation({ onSuccess: () => { toast.success("حُفظ ترتيب الفصول."); utils.admin.listChapters.invalidate(); } });
  const archive = trpc.admin.archiveNovel.useMutation({ onSuccess: () => { toast.success("أُرشفت الرواية وفصولها."); utils.admin.listNovels.invalidate(); } });
  const setNovel = <K extends keyof NovelForm>(key: K, value: NovelForm[K]) => setNovelForm(current => ({ ...current, [key]: value }));
  const setChapter = <K extends keyof ChapterForm>(key: K, value: ChapterForm[K]) => setChapterForm(current => ({ ...current, [key]: value }));
  const editNovel = (novel: NonNullable<typeof novels>[number]) => setNovelForm({ id: novel.id, authorId: String(novel.authorId), title: novel.title, subtitle: novel.subtitle || "", slug: novel.slug, shortDescription: novel.shortDescription || "", description: novel.description || "", coverMediaId: novel.coverMediaId ? String(novel.coverMediaId) : "", status: novel.status, isFeatured: novel.isFeatured });
  const editChapter = (chapter: NonNullable<typeof chapters>[number]) => setChapterForm({ id: chapter.id, title: chapter.title, slug: chapter.slug, sortOrder: String(chapter.sortOrder), content: chapter.content, excerpt: chapter.excerpt || "", status: chapter.status });
  const moveChapter = (id: number, direction: -1 | 1) => { if (!chapters || !selectedNovelId) return; const source = chapters.findIndex(chapter => chapter.id === id); const target = source + direction; if (source < 0 || target < 0 || target >= chapters.length) return; const order = [...chapters]; [order[source], order[target]] = [order[target], order[source]]; reorder.mutate({ novelId: selectedNovelId, orderedIds: order.map(chapter => chapter.id) }); };

  return <AdminShell title="الروايات والفصول" description="أنشئ العمل الأدبي، عدّل حالة النشر والمحتوى، ثم رتب الفصول كما تظهر للقارئ.">
    <div className="grid gap-7 xl:grid-cols-[390px_1fr]">
      <form className="rounded-2xl border border-[#1d2940]/10 bg-white p-5" onSubmit={event => { event.preventDefault(); if (!novelForm.authorId) return toast.error("اختر المؤلف أولًا."); createNovel.mutate({ id: novelForm.id, authorId: Number(novelForm.authorId), title: novelForm.title, subtitle: novelForm.subtitle || undefined, slug: novelForm.slug || undefined, shortDescription: novelForm.shortDescription || undefined, description: novelForm.description || undefined, coverMediaId: novelForm.coverMediaId ? Number(novelForm.coverMediaId) : null, status: novelForm.status, isFeatured: novelForm.isFeatured }); }}>
        <div className="flex items-center justify-between"><h2 className="font-serif text-2xl">{novelForm.id ? "تعديل رواية" : "رواية جديدة"}</h2><Plus className="h-5 w-5 text-[#af7c42]" /></div>
        <div className="mt-5 grid gap-3"><Select value={novelForm.authorId} onValueChange={value => setNovel("authorId", value)}><SelectTrigger><SelectValue placeholder="اختر المؤلف" /></SelectTrigger><SelectContent>{authors?.map(author => <SelectItem key={author.id} value={String(author.id)}>{author.displayName}</SelectItem>)}</SelectContent></Select><Input required value={novelForm.title} onChange={event => setNovel("title", event.target.value)} placeholder="عنوان الرواية" /><Input value={novelForm.subtitle} onChange={event => setNovel("subtitle", event.target.value)} placeholder="العنوان الفرعي" /><Input value={novelForm.slug} onChange={event => setNovel("slug", event.target.value)} placeholder="الرابط الثابت" /><MediaPicker label="غلاف الرواية" value={novelForm.coverMediaId} onChange={value => setNovel("coverMediaId", value)} /><Textarea value={novelForm.shortDescription} onChange={event => setNovel("shortDescription", event.target.value)} placeholder="نبذة قصيرة" /><Textarea value={novelForm.description} onChange={event => setNovel("description", event.target.value)} placeholder="وصف تفصيلي" className="min-h-24" /><Select value={novelForm.status} onValueChange={value => setNovel("status", value as PublicationStatus)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">مسودة</SelectItem><SelectItem value="review">قيد المراجعة</SelectItem><SelectItem value="published">منشورة</SelectItem><SelectItem value="unpublished">غير منشورة</SelectItem><SelectItem value="archived">مؤرشفة</SelectItem></SelectContent></Select></div>
        <button type="button" className="mt-4 text-sm font-semibold text-[#526071]" onClick={() => setNovel("isFeatured", !novelForm.isFeatured)}>{novelForm.isFeatured ? "★ رواية مميزة" : "☆ إضافة إلى المختارات"}</button><div className="mt-4 flex gap-2"><Button type="submit" className="bg-[#1d2940]" disabled={createNovel.isPending}>{createNovel.isPending ? "جارٍ الحفظ..." : "حفظ الرواية"}</Button>{novelForm.id && <Button type="button" variant="ghost" onClick={() => setNovelForm(freshNovel)}>إلغاء</Button>}</div>
      </form>
      <section className="rounded-2xl border border-[#1d2940]/10 bg-white p-5"><h2 className="font-serif text-2xl">أعمال المكتبة</h2><div className="mt-4 divide-y divide-[#1d2940]/8">{isLoading ? <p className="py-8 text-sm text-[#667085]">جارٍ التحميل...</p> : novels?.length ? novels.map(novel => <div key={novel.id} className={`flex flex-wrap items-center justify-between gap-4 py-4 ${selectedNovelId === novel.id ? "-mx-2 rounded-lg bg-[#e9dfca]/40 px-2" : ""}`}><button className="min-w-0 text-right" onClick={() => setSelectedNovelId(novel.id)}><strong className="block font-serif text-lg">{novel.title}</strong><small className="text-[#667085]">{novel.authorName} · {novel.chapterCount} فصلًا · {novel.status}</small></button><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => editNovel(novel)} aria-label="تعديل الرواية"><Edit3 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => setSelectedNovelId(novel.id)} aria-label="الفصول"><ListPlus className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => archive.mutate({ id: novel.id })} aria-label="أرشفة"><Archive className="h-4 w-4 text-[#a63a32]" /></Button></div></div>) : <p className="py-8 text-center text-sm text-[#667085]">أضف مؤلفًا ثم أنشئ أول رواية.</p>}</div></section>
    </div>
    {selectedNovelId && <section className="mt-7 grid gap-7 lg:grid-cols-[390px_1fr]">
      <form className="rounded-2xl border border-[#1d2940]/10 bg-white p-5" onSubmit={event => { event.preventDefault(); saveChapter.mutate({ id: chapterForm.id, novelId: selectedNovelId, title: chapterForm.title, slug: chapterForm.slug || undefined, sortOrder: Number(chapterForm.sortOrder), content: chapterForm.content, excerpt: chapterForm.excerpt || undefined, status: chapterForm.status }); }}><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-[#af7c42]" /><h2 className="font-serif text-2xl">{chapterForm.id ? "تعديل فصل" : "فصل جديد"}</h2></div><p className="mt-1 text-xs text-[#667085]">{selected?.title}</p><div className="mt-5 grid gap-3"><Input required value={chapterForm.title} onChange={event => setChapter("title", event.target.value)} placeholder="عنوان الفصل" /><Input value={chapterForm.slug} onChange={event => setChapter("slug", event.target.value)} placeholder="الرابط الثابت" /><Input required type="number" min="1" value={chapterForm.sortOrder} onChange={event => setChapter("sortOrder", event.target.value)} placeholder="ترتيب الفصل" /><Textarea required className="min-h-44" value={chapterForm.content} onChange={event => setChapter("content", event.target.value)} placeholder="محتوى الفصل العربي..." /><Textarea value={chapterForm.excerpt} onChange={event => setChapter("excerpt", event.target.value)} placeholder="مقتطف قصير" /><Select value={chapterForm.status} onValueChange={value => setChapter("status", value as PublicationStatus)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="draft">مسودة</SelectItem><SelectItem value="review">قيد المراجعة</SelectItem><SelectItem value="published">منشور</SelectItem><SelectItem value="unpublished">غير منشور</SelectItem><SelectItem value="archived">مؤرشف</SelectItem></SelectContent></Select></div><div className="mt-4 flex gap-2"><Button type="submit" className="bg-[#1d2940]">{chapterForm.id ? "تحديث الفصل" : "حفظ الفصل"}</Button>{chapterForm.id && <Button type="button" variant="ghost" onClick={() => setChapterForm({ ...freshChapter, sortOrder: String((chapters?.length || 0) + 1) })}>إلغاء</Button>}</div></form>
      <div className="rounded-2xl border border-[#1d2940]/10 bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl">فصول الرواية</h2><span className="text-xs text-[#667085]">حرّر أو رتّب الفصول</span></div><div className="mt-4 divide-y divide-[#1d2940]/8">{chapters?.length ? chapters.map((chapter, index) => <div key={chapter.id} className="flex items-center justify-between gap-3 py-3 text-sm"><button onClick={() => editChapter(chapter)} className="text-right hover:text-[#af7c42]"><b className="ml-2 text-[#af7c42]">{chapter.sortOrder}</b>{chapter.title}<small className="mr-2 text-[#667085]">{chapter.status}</small></button><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={() => editChapter(chapter)} aria-label="تحرير"><Edit3 className="h-4 w-4" /></Button><Button variant="ghost" size="icon" disabled={index === 0 || reorder.isPending} onClick={() => moveChapter(chapter.id, -1)} aria-label="نقل لأعلى"><ArrowUp className="h-4 w-4" /></Button><Button variant="ghost" size="icon" disabled={index === chapters.length - 1 || reorder.isPending} onClick={() => moveChapter(chapter.id, 1)} aria-label="نقل لأسفل"><ArrowDown className="h-4 w-4" /></Button></div></div>) : <p className="py-8 text-center text-sm text-[#667085]">أضف الفصل الأول لهذه الرواية.</p>}</div></div>
    </section>}
  </AdminShell>;
}
