import AdminShell from "@/components/AdminShell";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ImagePlus, Trash2, Upload } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

export default function AdminMedia() {
  const inputRef = useRef<HTMLInputElement>(null);
  const utils = trpc.useUtils();
  const { data } = trpc.media.list.useQuery();
  const [altText, setAltText] = useState("");
  const [mediaPendingDeletion, setMediaPendingDeletion] = useState<{ id: number; altText: string | null }>();
  const upload = trpc.media.upload.useMutation({ onSuccess: () => { toast.success("رُفعت الصورة وحُفظ مرجعها."); setAltText(""); if (inputRef.current) inputRef.current.value = ""; utils.media.list.invalidate(); }, onError: error => toast.error(error.message) });
  const deleteMedia = trpc.media.delete.useMutation({ onSuccess: () => { toast.success("حُذف مرجع الوسائط من المكتبة."); setMediaPendingDeletion(undefined); utils.media.list.invalidate(); }, onError: error => toast.error(error.message) });
  const handleFile = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => upload.mutate({ fileName: file.name, contentType: file.type as "image/jpeg" | "image/png" | "image/webp" | "image/gif", dataBase64: String(reader.result), altText: altText || undefined }); reader.readAsDataURL(file); };
  return <AdminShell title="مكتبة الوسائط" description="ارفع أغلفة الروايات وصور المؤلفين. الحذف يزيل المرجع من المكتبة فقط، ولا يتاح للصور المستخدمة حاليًا."><section className="rounded-2xl border border-[#1d2940]/10 bg-white p-6"><div className="flex items-center gap-2"><ImagePlus className="h-5 w-5 text-[#af7c42]" /><h2 className="font-serif text-2xl">رفع صورة</h2></div><p className="mt-2 text-sm text-[#667085]">الصيغ المدعومة: JPEG وPNG وWebP وGIF بحجم أقصى 3 ميغابايت.</p><div className="mt-5 flex flex-wrap items-center gap-3"><Input value={altText} onChange={event => setAltText(event.target.value)} placeholder="نص بديل وصفي (اختياري)" className="max-w-md" /><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={event => handleFile(event.target.files?.[0])} /><Button className="bg-[#1d2940]" onClick={() => inputRef.current?.click()} disabled={upload.isPending}><Upload className="ml-2 h-4 w-4" />{upload.isPending ? "جارٍ الرفع..." : "اختر صورة"}</Button></div></section><section className="mt-7"><h2 className="font-serif text-3xl">الملفات الأخيرة</h2><div className="mt-5 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-5">{data?.map(item => <article key={item.id} className="overflow-hidden rounded-xl border border-[#1d2940]/10 bg-white"><img src={item.url} alt={item.altText || "صورة مرفوعة"} className="aspect-square w-full object-cover" /><div className="flex items-center justify-between gap-2 p-3"><div className="min-w-0"><p className="text-xs font-bold">مرجع #{item.id}</p><p className="mt-1 truncate text-[11px] text-[#667085]">{item.mimeType}</p></div><Button type="button" variant="ghost" size="icon" className="text-destructive hover:bg-destructive/10 hover:text-destructive" aria-label={`حذف الوسائط ${item.id}`} onClick={() => setMediaPendingDeletion({ id: item.id, altText: item.altText })}><Trash2 className="h-4 w-4" /></Button></div></article>)}</div>{!data?.length && <p className="mt-5 text-sm text-[#667085]">لم تُرفع صور بعد.</p>}</section><AlertDialog open={Boolean(mediaPendingDeletion)} onOpenChange={open => !open && !deleteMedia.isPending && setMediaPendingDeletion(undefined)}><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>حذف الوسائط من المكتبة؟</AlertDialogTitle><AlertDialogDescription>سيُحذف سجل الملف من المكتبة فقط. إن كانت الصورة مستخدمة كغلاف رواية أو صورة مؤلف فسيُرفض الحذف لحماية المحتوى.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleteMedia.isPending}>إلغاء</AlertDialogCancel><AlertDialogAction className="bg-destructive text-destructive-foreground hover:bg-destructive/90" disabled={deleteMedia.isPending || !mediaPendingDeletion} onClick={event => { event.preventDefault(); if (mediaPendingDeletion) deleteMedia.mutate({ id: mediaPendingDeletion.id }); }}>{deleteMedia.isPending ? "جارٍ الحذف..." : "حذف المرجع"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></AdminShell>;
}
