import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Award, Bookmark, ClipboardCopy, ListPlus, Plus, Trophy } from "lucide-react";
import { useState } from "react";

export default function LibraryCommunityHub() {
  const utils = trpc.useUtils();
  const { data: achievements } = trpc.community.achievements.useQuery();
  const { data: readLater } = trpc.community.readLater.useQuery();
  const { data: lists } = trpc.community.myLists.useQuery();
  const { data: favorites } = trpc.library.favorites.useQuery({ sort: "recent" });
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [isPublic, setIsPublic] = useState(false);
  const [selectedList, setSelectedList] = useState("");
  const [selectedNovel, setSelectedNovel] = useState("");
  const refresh = () => { void utils.community.myLists.invalidate(); void utils.community.publicLists.invalidate(); };
  const createList = trpc.community.createList.useMutation({ onSuccess: () => { setName(""); setDescription(""); setIsPublic(false); refresh(); } });
  const addListItem = trpc.community.addListItem.useMutation({ onSuccess: refresh });
  const removeListItem = trpc.community.removeListItem.useMutation({ onSuccess: refresh });
  const toggleReadLater = trpc.community.toggleReadLater.useMutation({ onSuccess: () => utils.community.readLater.invalidate() });
  const shareList = async (id: number) => { await navigator.clipboard.writeText(`${window.location.origin}/lists/${id}`); };
  const challengePercent = Math.min(100, Math.round(((achievements?.stats.monthlyCompleted ?? 0) / (achievements?.stats.target ?? 3)) * 100));
  return <section className="container pb-8"><div className="grid gap-5 xl:grid-cols-3"><article className="rounded-2xl border border-[#af7c42]/25 bg-[#af7c42]/5 p-5"><div className="flex items-center gap-2"><Trophy className="h-5 w-5 text-[#af7c42]" /><h2 className="font-serif text-2xl text-[#1d2940]">تحدي الشهر</h2></div><p className="mt-2 text-sm text-[#667085]">أكمل 3 روايات خلال هذا الشهر لتحصل على شارة التحدي.</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-white"><div className="h-full bg-[#af7c42] transition-all" style={{ width: `${challengePercent}%` }} /></div><div className="mt-2 flex justify-between text-xs text-[#667085]"><span>{achievements?.stats.monthlyCompleted ?? 0} من {achievements?.stats.target ?? 3}</span><strong className="text-[#af7c42]">{challengePercent}%</strong></div><div className="mt-4 flex flex-wrap gap-2">{achievements?.achievements.map(item => <span key={item.key} title={item.description} className={`rounded-full px-2.5 py-1 text-xs ${item.earnedAt ? "bg-[#1d2940] text-white" : "bg-white text-[#667085]"}`}><Award className="ml-1 inline h-3.5 w-3.5" />{item.title}</span>)}</div></article>
    <article className="rounded-2xl border border-[#1d2940]/10 bg-white p-5"><div className="flex items-center gap-2"><Bookmark className="h-5 w-5 text-[#af7c42]" /><h2 className="font-serif text-2xl text-[#1d2940]">اقرأ لاحقًا</h2></div><div className="mt-4 space-y-2">{readLater?.length ? readLater.slice(0, 4).map(item => <div key={item.novelId} className="flex items-center justify-between gap-2 rounded-xl bg-[#fbf8f2] p-3"><div className="min-w-0"><strong className="block truncate text-sm text-[#1d2940]">{item.title}</strong><span className="text-xs text-[#667085]">{item.authorName}</span></div><Button size="sm" variant="ghost" className="h-7 text-xs text-[#8f4b42]" onClick={() => toggleReadLater.mutate({ novelId: item.novelId })}>إزالة</Button></div>) : <p className="rounded-xl bg-[#fbf8f2] p-3 text-sm text-[#667085]">أضف الروايات التي تريد العودة إليها لاحقًا من صفحة الرواية.</p>}</div></article>
    <article className="rounded-2xl border border-[#1d2940]/10 bg-white p-5"><div className="flex items-center gap-2"><ListPlus className="h-5 w-5 text-[#af7c42]" /><h2 className="font-serif text-2xl text-[#1d2940]">قوائمي العامة</h2></div><form className="mt-4 grid gap-2" onSubmit={event => { event.preventDefault(); if (name.trim()) createList.mutate({ name: name.trim(), description: description.trim() || undefined, isPublic }); }}><input value={name} onChange={event => setName(event.target.value)} placeholder="مثل: أفضل روايات الغموض" className="rounded-lg border border-[#1d2940]/15 px-3 py-2 text-sm text-[#1d2940] outline-none" /><input value={description} onChange={event => setDescription(event.target.value)} placeholder="وصف اختياري" className="rounded-lg border border-[#1d2940]/15 px-3 py-2 text-sm text-[#1d2940] outline-none" /><label className="flex items-center gap-2 text-xs text-[#667085]"><input type="checkbox" checked={isPublic} onChange={event => setIsPublic(event.target.checked)} />إتاحة المشاركة العامة</label><Button type="submit" size="sm" className="bg-[#af7c42] text-white hover:bg-[#936536]" disabled={!name.trim() || createList.isPending}><Plus className="ml-1 h-4 w-4" />إنشاء قائمة</Button></form></article></div>
    {lists?.length ? <div className="mt-5 rounded-2xl border border-[#1d2940]/10 bg-white p-5"><div className="flex flex-wrap items-center gap-2"><strong className="font-serif text-xl text-[#1d2940]">إدارة قوائمك</strong><select value={selectedList} onChange={event => setSelectedList(event.target.value)} className="rounded-lg border border-[#1d2940]/15 px-2 py-1.5 text-xs text-[#1d2940]"><option value="">اختر قائمة</option>{lists.map(list => <option key={list.id} value={list.id}>{list.name}{list.isPublic ? " · عامة" : " · خاصة"}</option>)}</select><select value={selectedNovel} onChange={event => setSelectedNovel(event.target.value)} className="rounded-lg border border-[#1d2940]/15 px-2 py-1.5 text-xs text-[#1d2940]"><option value="">أضف من المفضلة…</option>{favorites?.map(novel => <option key={novel.novelId} value={novel.novelId}>{novel.title}</option>)}</select><Button size="sm" variant="outline" disabled={!selectedList || !selectedNovel || addListItem.isPending} onClick={() => addListItem.mutate({ listId: Number(selectedList), novelId: Number(selectedNovel) })}>إضافة رواية</Button></div>{lists.map(list => <div key={list.id} className="mt-4 rounded-xl bg-[#fbf8f2] p-4"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-[#1d2940]">{list.name}</strong>{list.isPublic ? <Button size="sm" variant="ghost" className="h-7 px-2 text-xs text-[#af7c42]" onClick={() => shareList(list.id)}><ClipboardCopy className="ml-1 h-3.5 w-3.5" />نسخ رابط المشاركة</Button> : <span className="text-xs text-[#667085]">خاصة</span>}</div><div className="mt-2 flex flex-wrap gap-2">{list.items.length ? list.items.map(item => <span key={item.novelId} className="inline-flex items-center gap-1 rounded-full bg-white px-2.5 py-1 text-xs text-[#53627a]">{item.title}<button type="button" className="text-[#8f4b42]" onClick={() => removeListItem.mutate({ listId: list.id, novelId: item.novelId })}>×</button></span>) : <span className="text-xs text-[#667085]">أضف روايات من المفضلة لبدء هذه القائمة.</span>}</div></div>)}</div> : null}
  </section>;
}
